### ISSUE TITLE
Question regarding reproducing the results

### ISSUE THREAD

**Issue by sxy7147** [markusgrotz/peract_bimanual#12]
Hi, authors:

We are working on reproducing the training results of the **ACT_BC_LANG** and **BIMANUAL_PERACT** models provided. We trained both models for 100k steps on the **'lift ball'** and **'push box'** tasks (single task), but we observed a 0% success rate in our tests for each model. We are unsure if we encountered an issue during our reproduction process, and we would greatly appreciate your insights on this matter.

Regarding the specifics of our training commands:

1. We modified the config based on the discussion in https://github.com/markusgrotz/peract_bimanual/issues/7.
2. The commands we used for training and testing were as follows:
* Training: python train.py method=BIMANUAL_PERACT rlbench.tasks=[coordinated_push_box]
* Testing: python eval.py method=BIMANUAL_PERACT rlbench.tasks=[coordinated_push_box] cinematic_recorder.enabled=True

Could you kindly provide any thoughts or suggestions? Additionally, if possible, could you share the pretrained checkpoints with us? This would be immensely helpful.

Thank you very much for your assistance.

**Comment by YuyinYang2003** [comment]
Did you visualize the performance of the model by setting 'cinematic_recorder: enabled: True' in the config?

**Comment by markusgrotz** [comment]
I updated the documentation and will continue to improve the document. You need to set the action modes. This setting depends on the method as they use different control methods for the robot. For **BIMANUAL_PERACT** this is:

```
rlbench:
  gripper_mode: 'BimanualDiscrete'
  arm_action_mode: 'BimanualEndEffectorPoseViaPlanning'
  action_mode: 'BimanualMoveArmThenGripper'
```


For **ACT_BC_LANG** it is:



```
rlbench:
  gripper_mode: 'BimanualGripperJointPosition'
  arm_action_mode: 'BimanualJointPosition'
  action_mode: 'BimanualJointPositionActionMode'
```

Please note that also have to set the episode_length parameter. I will update the documentation for ACT soon.

Regarding your question about the evaluation. I highly recommend disabling the cinematic recorder if not needed. Depending on the task running 100 episodes for the eval takes like 10 minutes. If the cinematic recorder is enabled this is significantly larger.
