### ISSUE TITLE
[Eval] How to choose the best checkpoint in the paper?

### ISSUE THREAD

**Issue by aopolin-lv** [markusgrotz/peract_bimanual#6]
Hello, after completing the training of the model, I don't know how to choose the right ckpt. So, I would appreciate it if I could answer any questions.

1. When evaluating and testing, do you execute the `eval.py` script on the ckpt saved every 10k steps to select the ckpt with the highest score, after the training process completed? Specifically, given the number of training steps is 40k, the ckpt with 10k, 20k, 30k, and 40k will be evaluated one by one, and the ckpt with the highest score will be selected for the final test on the testset.

2. How can I improve the speed of testing? Specifically, when I run the `eval.py` script, it takes 1 hour to complete 25 episodes of a single task. The hardware I'm using includes an Intel-8352V CPU with 72 cores and an A800-80G GPU with performance similar to the A100-80G. May I ask what your typical efficiency is when running `eval.py`?

**Comment by aopolin-lv** [comment]
By the way, the valiadation sets has not been accessed from the ftp server. Could you please upload the relevant datasets?

**Comment by markusgrotz** [comment]
1. **Training**: I use SLURM for launching my jobs for training/evaluation. Everything is pretty automated. I will provide some details soon. The code / documentation is still work in progress and I hope I can find more time to work on that soon.
2. **Evaluation**: That is too slow. Do you have more insights on the setup? Is it a headless setup?
3. **Dataset**: I haven actively looking for an alternative hosting option and transfered the data today to https://dataset.cs.washington.edu/fox/bimanual/

Let me know if that helps

**Comment by aopolin-lv** [comment]
Thank you for your reply. The data download is now very convenient! However, I still have some doubts about the time consumption for training/evaluating.

1. Training: I used the _bimanual_peract_ configuration with a `batch_size` of 4, which occupied about 46GB of GPU memory. Training for 40k iterations took approximately 15-16 hours.
2. Evaluating: I used 25 episodes, with each task taking about 1 hour.
Everything was done under the headless setting. 

The paper mentions that using the bimanual setting would result in a total training time of about **54 hours**. However, my single-task training takes 15 hours, and the total training time for all tasks is 15 * 13 = 195 hours, which far exceeds the time reported in the paper. Is there anything I should improve? And the evaluating period also takes too much time, how can I do to reduce the cost?

Below are my specific training configuration items.

---
**config.yaml**
```
ddp:
    master_addr: "localhost"
    master_port: "0"
    num_devices: 1

rlbench:
    task_name: "multi"
    tasks: [coordinated_lift_ball]
    demos: 100
    demo_path: /data/aopolin/project/peract_bimanual/bimanual_data/train
    episode_length: 25
    cameras: ["over_shoulder_left", "over_shoulder_right", "overhead", "wrist_right", "wrist_left", "front"]
    camera_resolution: [256, 256]
    scene_bounds: [-0.3, -0.5, 0.6, 0.7, 0.5, 1.6]
    include_lang_goal_in_obs: True

replay:
    batch_size: 4
    timesteps: 1
    prioritisation: False
    task_uniform: True # uniform sampling of tasks for multi-task buffers
    use_disk: True
    path: '/data/aopolin/project/peract_bimanual/replay' # only used when use_disk is True.
    max_parallel_processes: 32

framework:
    log_freq: 100
    save_freq: 100
    train_envs: 1
    replay_ratio: ${replay.batch_size}
    transitions_before_train: 200
    tensorboard_logging: True
    csv_logging: True
    training_iterations: 40000
    gpu: 0
    env_gpu: 0
    logdir: '/data/aopolin/project/peract_bimanual/logs/0820-1508/coordinated_lift_ball/'
    logging_level: 20 # https://docs.python.org/3/library/logging.html#levels
    seeds: 1
    start_seed: 0
    load_existing_weights: True
    num_weights_to_keep: 60 # older checkpoints will be deleted chronologically
    num_workers: 4
    record_every_n: 5
    checkpoint_name_prefix: "checkpoint"

defaults:
    - method: BIMANUAL_PERACT

hydra:
    run:
        dir: ${framework.logdir}/${rlbench.task_name}/${method.name}
```
---
**eval.yaml**
```
defaults:
    - method: BIMANUAL_PERACT


rlbench:
    task_name: "multi"
    tasks: [coordinated_lift_ball]
    demo_path: /data/aopolin/project/peract_bimanual/bimanual_data/test
    episode_length: 25
    cameras: ["over_shoulder_left", "over_shoulder_right", "overhead", "wrist_right", "wrist_left", "front"]
    camera_resolution: [256, 256]
    scene_bounds: [-0.3, -0.5, 0.6, 0.7, 0.5, 1.6]
    include_lang_goal_in_obs: True
    time_in_state: True
    headless: True
    gripper_mode: 'BimanualDiscrete'
    arm_action_mode: 'BimanualEndEffectorPoseViaPlanning'
    action_mode: 'BimanualMoveArmThenGripper'

framework:
    tensorboard_logging: True
    csv_logging: True
    gpu: 0
    logdir: '/data/aopolin/project/peract_bimanual/logs/0820-1508/coordinated_lift_ball/'
    start_seed: 0
    record_every_n: 5

    eval_envs: 1
    eval_from_eps_number: 0
    eval_episodes: 25
    eval_type: 38500 # or 'best', 'missing', or 'last'
    eval_save_metrics: True

cinematic_recorder:
    enabled: False
    camera_resolution: [1280, 720]
    fps: 30
    rotate_speed: 0.005
    save_path: '/data/aopolin/project/peract_bimanual/videos/'
```
